export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'
export const CATEGORY_DETAILS_RESET = 'CATEGORY_DETAILS_RESET'

export const CATEGORY_PRODUCTS_REQUEST = 'CATEGORY_PRODUCTS_REQUEST'
export const CATEGORY_PRODUCTS_SUCCESS = 'CATEGORY_PRODUCTS_SUCCESS'
export const CATEGORY_PRODUCTS_FAIL = 'CATEGORY_PRODUCTS_FAIL'

export const CATEGORY_TOP_REQUEST = 'CATEGORY_TOP_REQUEST'
export const CATEGORY_TOP_SUCCESS = 'CATEGORY_TOP_SUCCESS'
export const CATEGORY_TOP_FAIL = 'CATEGORY_TOP_FAIL'