export const REPORT_AVERAGE_REQUEST = 'REPORT_AVERAGE_REQUEST'
export const REPORT_AVERAGE_SUCCESS = 'REPORT_AVERAGE_SUCCESS'
export const REPORT_AVERAGE_FAIL = 'REPORT_AVERAGE_FAIL'
export const REPORT_AVERAGE_RESET = 'REPORT_AVERAGE_RESET'
export const REPORT_LOWINV_REQUEST = 'REPORT_LOWINV_REQUEST'
export const REPORT_LOWINV_SUCCESS = 'REPORT_LOWINV_SUCCESS'
export const REPORT_LOWINV_FAIL = 'REPORT_LOWINV_FAIL'
export const REPORT_LOWINV_RESET = 'REPORT_LOWINV_RESET'

